### ISSUE TITLE
For loop could exceed block gas limit

### ISSUE THREAD

**Issue by pauliax** [vrexlab/dyverse-bounty#1]
contract KydyOwnership
function tokensOfOwner

`for (kydyId = 1; kydyId <= totalKydys; kydyId++)`

Be careful when using loops, as if it iterates through many items, the execution may exceed the block gas limit, consume all the gas provided and fail. Carefully test how many items at maximum you can pass to such functions to make it successful. totalKydys eventually could grow so large as to make future operations of the contract cost too much gas to fit in a block. Also, take into consideration that test networks (example, Rinkeby) could have different block gas limit than the main network.

**Comment by ouoabcde** [comment]
Thanks for your consideration. We care about this function should not be called inside the contract. If it does, it will spend lots of gas like you told. This is `external view` function, so it will not spend any gas when it's called outside of the contract like in web3.js. For more caution, I'll add some more warning comments on this function. When I PR the change about this, I'll tag you to know 👍

**Comment by pauliax** [comment]
You may be right, here is an interesting discussion: https://github.com/PolymathNetwork/polymath-core/issues/54#issuecomment-380048633
but for the sake of curiosity, have you tried creating >10'000 kydys and then execute this function (not from the contract)?

**Comment by ouoabcde** [comment]
Oh, I didn't try that much yet. I read the link, and there says,
~~~
Calling doWork(10000) as a transaction (on Ropsten) fails with an Out of Gas error - e.g.:
https://ropsten.etherscan.io/tx/0xfe95eb83600b9a49f73c4dc536a55f2fd30b6c12864c00016ee278be23a1023b

Calling doWork(10000) as a call (rather than transaction) works regardless of what value you pass to doWork.
~~~
According to this, `tokensOfOwner` function would pass with no error no matter what the value is. Because this function is `view` type which is just for `call`. So I think there would be no problem on this.
